language: java

jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script: pwd && ls -al && cd ProjectCI && mvn clean test-compile test && mvn cobertura:cobertura

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'

after_failure:
  - echo $TRAVIS_TEST_RESULT
  
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN     # $key_api you should create in heroku.After that, you must paste this variable, Environment Variables section in your project on Travis-CI 
  skip_cleanup: true
  app: githubciitest
after_deploy:
    - cd .. && chmod 777 $(pwd)/first.sh && $(pwd)/first.sh
    - pwd && ls -al
